#!/bin/bash
# Purpose - Script to add a user to Linux system including passsword
# ------------------------------------------------------------------

# Am i Root user?
if [ $(id -u) -eq 0 ]; then

	username_pocteg='pocteg'
	read -s -p "Enter password pocteg: " password_pocteg
	read -p "Enter ssh key pocteg: " sshkey_pocteg
	
	username_jenkinsftl='jenkinsftl'
	password_jenkinsftl='j3nk1n$ftL'
	read -p "Enter ssh key jenkins: " sshkey_jenkinsftl

	egrep "^$username_pocteg" /etc/passwd >/dev/null
	if [ $? -eq 0 ]; then
		echo "$username_pocteg exists!"
	else
		pass_pocteg=$(perl -e 'print crypt($ARGV[0], "password")' $password_pocteg)
		useradd -m -p "$pass_pocteg" "$username_pocteg"
		
		if [ $? -eq 0 ]; then
			echo "User has been added to system!"
		else 
			echo "Failed to add a user!"
			echo "exit"
			return 2
		fi

		mkdir /home/"$username_pocteg"/.ssh		
		cat /dev/null > /home/"$username_pocteg"/.ssh/authorized_keys
		echo "$sshkey_pocteg" >> /home/"$username_pocteg"/.ssh/authorized_keys
		chown "$username_pocteg":"$username_pocteg" /home/"$username_pocteg"/.ssh
		chown "$username_pocteg":"$username_pocteg" /home/"$username_pocteg"/.ssh/authorized_keys
	fi	
		
	usermod -a -G sudo "$username_pocteg"
	id "$username_pocteg"


	egrep "^$username_jenkinsftl" /etc/passwd >/dev/null
	if [ $? -eq 0 ]; then
		echo "$username_jenkinsftl exists!"
	else
		pass_jenkinsftl=$(perl -e 'print crypt($ARGV[0], "password")' $password_jenkinsftl)
		useradd -m -p "$pass_jenkinsftl" "$username_jenkinsftl"
		
		if [ $? -eq 0 ]; then
			echo "User has been added to system!"
		else 
			echo "Failed to add a user!"
			echo "exit"
			return 2
		fi

		mkdir /home/"$username_jenkinsftl"/.ssh		
		cat /dev/null > /home/"$username_jenkinsftl"/.ssh/authorized_keys
		echo "$sshkey_jenkinsftl" >> /home/"$username_jenkinsftl"/.ssh/authorized_keys
		chown "$username_jenkinsftl":"$username_jenkinsftl" /home/"$username_jenkinsftl"/.ssh
		chown "$username_jenkinsftl":"$username_jenkinsftl" /home/"$username_jenkinsftl"/.ssh/authorized_keys
	fi	
		
	usermod -a -G sudo "$username_jenkinsftl"
	id "$username_jenkinsftl"
	

else
	echo "Only root may add a user to the system."
	echo "exit"
	exit 2
fi